config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  resources :renters do
    resources :review, except: [:index, :show]
    collection do
      get 'search'
    end
  end

  root 'renters#index'
  
  match '/about_us', to: 'pages#about_us', via: :get
  match '/contact_us', to: 'pages#contact_us', via: :get
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base

	belongs_to :review

end

app/models/renters.rb
class Renters < ActiveRecord::Base
	
	has_many :review
  validates_uniqueness_of :license_no, :message => 'of Renter already exists, please use the search button'
  validates_presence_of :fname
  validates_presence_of :lname
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :license_no

  geocoded_by :full_address
  after_validation :geocode 

  def full_address
    [city, state].join(',')
  end

  def self.search(params)
    license_query = "%#{params[:license]}%"
    id_query = "%#{params[:id]}%"
    renters = Renters.where("license_no LIKE ?", license_query) if params[:license].present?
    #renters = Renters.where("id LIKE ?", id_query) if params[:id].present?
    #renters = Renters.where("name LIKE ? or description LIKE ?", "%#{{params[:search]}}%", "%#{{params[:search]}}%") if params[:search].present?
    #renters = Renters.near(params[:location], 20) if params[:location].present?
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
	belongs_to :renters
  has_many :property_type

  validates_presence_of :comment
  validates_presence_of :rating
  validates_presence_of :years
  validates_presence_of :address1
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zipcode
  validates_presence_of :property_type_id

  geocoded_by :full_address
  after_validation :geocode 

  def full_address
    [address1, address2, city, state, zipcode].join(',')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :review
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :add_parameters_to_user, if: :devise_controller?

  def add_parameters_to_user
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about_us
	end

	def contact_us
	end
	
end

app/controllers/property_type_controller.rb
class PropertyTypeController < ApplicationController
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :show]
  before_action :is_admin?, only: [:edit, :update, :destroy]

	def index
    #visitor_lat = request.location.latitude
    #visitor_long = request.location.longitude
    #hard-coded location to San Jose, CA for testing purposes
    visitor_lat = 37.3382
    visitor_long = -121.8863
    search_range = 50 #distance from visitor location in miles

    @renters = Renters.near([visitor_lat, visitor_long], search_range)
    @renter = Renters.search(params)
    @reviews = Review.where(renters_id: @renter)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
	end

  def new
    @renter = Renters.new
  end

  def create
    @renter = Renters.new(renter_params)
    if @renter.save
      redirect_to @renter
    else
      flash[:danger] = @renter.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @renter = Renters.find(params[:id])
    @reviews = Review.where(renters_id: @renter)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def search
    @renter = Renters.search(params)
    @reviews = Review.where(renters_id: @renter)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def edit
    @renter = Renters.find(params[:id])
  end

  def update
    @renter = Renters.find(params[:id])
    @renter.update(renter_params)
    redirect_to @renter
  end

  def destroy
    @renter = Renters.find(params[:id])
    @renter.destroy
    redirect_to root_path 
  end

  private
    def renter_params
      params.require(:renters).permit(:fname, :lname, :license_no, :description, :city, :state, :phone, :email)
    end

    def is_admin?
      if !current_user.try(:admin?)
        flash[:danger] = "You do not have the correct privilidges"
        redirect_back(fallback_location: root_path)
      end
    end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action :set_renter
  before_action :authenticate_user!
  before_action :req_authentication, only: [:edit, :update, :destroy]

  def new
    @review = Review.new(renters: @renter)
  end

  def create
    @review = current_user.review.build(review_params)
    @review.renters = @renter
    if @review.save 
      @renter.update(renter_params)
      redirect_to @renter 
    else
      flash[:danger] = @review.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to @renter
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @renter 
  end

  private
    def set_renter
      @renter = Renters.find(params[:renter_id])
    end

    def req_authentication
      @review = Review.find(params[:id])
      if !current_user.try(:admin?) && current_user.id != @review.user.id
        flash[:danger] = "You do not have the correct privilidges"
        redirect_back(fallback_location: root_path)
      end
    end

    def review_params
      params.require(:review).permit(:comment, :rating, :years, :property_type_id, :address1, :address2, :city, :state, :zipcode)
    end

    def renter_params
      params.require(:review).permit(:city, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_header.html.erb
<!-- begin header -->
<header>
  <div class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li>
              <%= link_to root_path do %>
              <i class="fa fa-home" aria-hidden="true"></i>
              <% end %>
            </li>
            <li><%= link_to "About Us", about_us_path %></li>
            <li><%= link_to "Contact Us", contact_us_path %></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>
  </div>
</header>  
<!-- end header -->

app/views/layouts/_javascript_footer.html.erb
<!-- Javascript  -->
  <script src="js/jquery.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.placeholder.js"></script>
	<script src="js/custom.js"></script> 

app/views/layouts/_login_alerts.html.erb
<div class="container"> 
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
  <% end %>
</div>

app/views/layouts/_logo_container.html.erb
  <div id="logo-container">
    <div class="container">
      <div class="row">
        <div class="span8">
          <%= link_to "Renter Reviews", root_path, class: "brand logo-text" %>
          <span class="tag-line hidden-phone">Get a review before renting out</span>
        </div>
        <div class="span4">
          <ul class="inline pull-right">
            <% if user_signed_in? %>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul> 
        </div>
      </div>
    </div>
  </div>
  <!-- #logo-container -->

app/views/renters/index.html.erb
<div id="home-search-container">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="widget pull-right">
          <div class="row">
            <div class="span12 head-container">
              <div class="row">
                <div class="span8 hidden-phone">
                  <h2 class="head-title">Welcome to Renter Reviews</h2>
                  <p class="head-message"><strong>Renter Reviews - Check your renters beyond their credit score.</strong><br />
                  Real reviews from real landlords about their experience with the renter.</p>
                  <%= link_to "Add a New Renter", new_renter_path, class: "btn btn-large btn-realto span3 header-cta"%>
                </div>
                <div class="span4" style="padding-bottom: 150px;">
                  <div class="search-form">
                    <p>Find your next renter</p>
                    <%= form_tag search_renters_path, method: :get do |f| %>
                      <%= text_field_tag :license, nil, placeholder: "Driver's License" %>
                      <%#= text_field_tag :id, nil, placeholder: "ID number" %>
                      <%# <%= text_field_tag :search, nil, placeholder: "John Doe" %>
                      <%# <%= text_field_tag :location, nil, placeholder: "Los Angeles, CA" %> 
                      <%= submit_tag 'Search', name: nil, class: "btn span2 btn-realto-form btn-large" %>
                    <% end %>
                  </div>
                  <!-- .search-form -->   
                </div>
                <!-- .span4 -->
              </div>
            </div>        
          </div>
          <!-- .row -->
        </div>
        <!-- .search-holder -->
      </div>
      <!-- .span12 -->
    </div>
    <!-- .row -->
  </div>
  <!-- .container -->
</div>
<div id="latest-properties">
  <div class="container">
    <div class="row">
      <div class="span12">
        <h2 class="secion-title">Recent Reviews</h2>
      </div>
    </di        
    <!-- Begin Carousel -->
    <div class="row">
      <div id="realto-carousel" class="carousel slide span12">
        <div class="carousel-navigation pull-right">
          <a class="left carousel-control pull-left" href="#realto-carousel" data-slide="prev">‹</a>
          <a class="right carousel-control pull-right" href="#realto-carousel" data-slide="next">›</a>
        </div>
        <div class="carousel-inner">
          <div class="item active">
            <ul class="thumbnails">
              <% @renters.last(3).each do |r| %>
                <li class="span4 box-container">
                  <div class="holder">
                    <a class="overlay" title="property title" href="#">
                      <span class="more"></span>
                      <%= link_to image_tag("http://placehold.it/370x210"), r %>
                    <span class="prop-tag">Nearby</span>
                    <div class="prop-info">
                      <h3 class="prop-title"><%= link_to (r.fname.titleize + " " + r.lname.titleize), r %></h3>
                      <ul class="more-info clearfix">
                        <li class="info-label clearfix">
                          <span class="pull-left">Rating:</span> 
                          <% if r.review.present? %>
                            <span class="prop-price pull-right serif italic star-rating" data-score=<%= r.review.average(:rating).round(2) %>></span>
                          <% else %>
                            <span class="prop-price pull-right serif italic star-rating" data-score=0></span>
                          <% end %>                                                  
                        <li class="info-label clearfix"><span class="pull-left">Location:</span> <span class="qty pull-right"><%= r.city.titleize %>, <%= r.state.upcase %></span></li>
                      </ul>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          </div><!-- .item -->
          <div class="item">
            <ul class="thumbnails">
              <% if @renters.size > 3 %>
                <% @renters.order(:id).reverse_order.limit(3).offset(3).each do |r| %>
                  <li class="span4 box-container">
                  <div class="holder">
                      <a class="overlay" title="property title" href="#">
                      <span class="more"></span>
                        <%= link_to image_tag("http://placehold.it/370x210"), r %>
                      <span class="prop-tag">Nearby</span>
                      <div class="prop-info">
                        <h3 class="prop-title"><%= link_to (r.fname.titleize + " " + r.lname.titleize), r %> <%= link_to r.lname, r %></h3>
                        <ul class="more-info clearfix">
                          <li class="info-label clearfix"><span class="pull-left">Rating:</span> 
                          <% if r.review.present? %>
                            <span class="prop-price pull-right serif italic star-rating" data-score=<%= r.review.average(:rating).round(2) %>></span>
                          <% else %>
                            <span class="prop-price pull-right serif italic star-rating" data-score=0></span>
                          <% end %>
                          <li class="info-label clearfix"><span class="pull-left">Location:</span> <span class="qty pull-right"><%= r.city.titleize %>, <%= r.state.upcase %></span></li>
                        </ul>
                      </div>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <li class="info-label clearfix">
                  <h5 class="prop-title">No other renters nearby.</h5>
                </li>
              <% end %>
            </ul>
          </div><!-- .item -->                 
        </div><!-- .carousel-inner -->
      </div>
    </div><!--End Carousel-->        
  </div><!--container  -->
</div><!-- #latest-properties  -->     
<!-- #latest-properties  -->
<div class="container">
  <div class="row">
    <div class="home-bottom-top">
      <div class="span4">
        <div class="info-box">
          <h2 class="secion-title">Why choose us?</h2>
          <p>&nbsp;&nbsp;&nbsp;&nbsp;Never get a bad renter that abuses your property again.</p>
          <a class="serif italic" title="Continue"><%= link_to "Continue", about_us_path %> &raquo;</a>
        </div>
      </div>
      <!-- .span4 -->
      <div class="span4">
        <div class="info-box">
          <h3 class="info-head">Have questions?</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-briefcase"></i>
            </div>
            <div class="info-box">
            <p>Feel free to contact us anytime</p>
              <a class="serif italic" title="Contact Us"><%= link_to "Contact", contact_us_path %> &raquo;</a>
            </div>
          </div>
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
      </div>
      <!-- .span4 -->
      <div class="span4">
        <div class="info-box">
          <h3 class="info-head">Add More details here</h3>
          <div class="row clearfix">
            <div class="pull-left icons hidden-phone">
              <i class="icon-move"></i>
            </div>
            <div class="info-box">
              <p>Lorem ipsum dolor sit amet consectetur incididunt ut labore et dolore
                magna aliqua adipisicing elit seddo eiusmod tempor.</p>
              <a class="serif italic" href="#" title="Continue">Continue &raquo;</a>
            </div>
          </div>
          <!-- .clearfix -->
        </div>
        <!-- .info-box -->
      </div>
      <!-- .span4 -->
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span8">
      <h2 class="secion-title">Meet our agents</h2>
      <div class="row">
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" src="http://placehold.it/170x170" class="media-object">
            </a>
            <p class="home-agent-name">John Doe</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div>
          <!-- .home-agents -->
        </div>
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" src="http://placehold.it/170x170" class="media-object">
            </a>
            <p class="home-agent-name">Susan Underwood</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div>
          <!-- .home-agents -->
        </div>
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" src="http://placehold.it/170x170" class="media-object">
            </a>
            <p class="home-agent-name">Erik Peterson</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div>
          <!-- .home-agents -->
        </div>
        <div class="span2">
          <div class="home-agents widget">
            <a class="overlay" href="#" title="agent name">
              <span class="more"></span>
              <img alt="image" src="http://placehold.it/170x170" class="media-object">
            </a>
            <p class="home-agent-name">Lu Jackson</p>
            <a class="serif italic" href="#" title="View profile page">View profile
              page &raquo;</a>
          </div>
          <!-- .home-agents -->
        </div>
      </div>
    </div>
    <!-- .span8  -->
    <div class="span4">
      <div class="home-blog-articles widget">
        <h2 class="secion-title">Articles from the Blog</h2>
        <ul>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Lorem ipsum dolor sit amet, consectetur
              adipiscing</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Duis suscipit venenatis pellentesque tempor
              libero</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Etiam aliquet aliquam metus in tristique</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Cras venenatis pellentesque venenatis
              pellentesque</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Vivamus vitae venenatis pellentesque nunc sed
              nisl</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">In tempus venenatis pellentesquetempor</a></li>
          <li>
            <i class="icon-caret-right"></i>
            <a title="title" href="#">Suspendisse vulputate venenatis pellentesque
              quis</a></li>
        </ul>
      </div>
    </div>
    <!-- .span4  -->
  </div>
</div>     

app/views/renters/show.html.erb
<%# page for displaying renter and values.%>
<div class="container page-content">
    <div class="row">
        <div class="span8">
            <div class="box-container">
                <div id="adv-custom-pager"></div>
                <div class="clearfix">
                    <div class="clearfix padding30">
                        <h2 class="prop-title pull-left margin0"><%= @renter.fname %> <%= @renter.lname %>
                          <% if current_user.try(:admin?) %>
                            <small><%= link_to "Edit", edit_renter_path, class: "btn btn-primary btn-mini" %></small>
                            <small><%= link_to "Delete", renter_path, method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-danger btn-mini" %></small>
                          <% end %>
                        </h2>
                        <span class="prop-price pull-right serif italic star-rating" data-score=<%= @avg_rating %>></span>                        
                    </div>
                    <div class="clearfix padding030 row-fluid">
                        <ul class="more-info pull-left span6">
                            <li class="info-label clearfix">
                              <span class="pull-left">
                                Driver's License No:
                              </span>
                              <span class="qty pull-right">
                                <%= @renter.license_no.upcase %>                                  
                              </span>
                            </li>
                            <li class="info-label clearfix">
                              <span class="pull-left">
                               Phone:
                              </span>
                              <span class="qty pull-right">
                                <%= number_to_phone(@renter.phone) %>
                              </span>
                            </li>
                            <li class="info-label clearfix">
                              <span class="pull-left">
                                Email:
                              </span>
                              <span class="qty pull-right">
                               <%= mail_to(@renter.email) %>
                              </span>
                            </li>
                        </ul>
                        <ul class="more-info pull-right span6">
                            <li class="info-label clearfix">
                              <span class="pull-left">
                                City:
                              </span>
                              <span class="qty pull-right">
                                <%= @renter.city.titleize %>
                              </span>
                            </li>
                            <li class="info-label clearfix">
                              <span class="pull-left">
                                State:
                              </span>
                              <span class="qty pull-right">
                                <%= @renter.state.upcase %>
                              </span>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix padding30">
                        <h3>Description</h3>
                        <p><%= simple_format(@renter.description) %>
                        </p>
                    </div>
                    <div class="clearfix padding30">
                        <%= link_to "Write a Review", new_renter_review_path(@renter), class: "btn btn-small btn-realto"%>
                        <h3>Reviews</h3>
                        <% if @reviews.blank? %>
                          <p>No reviews yet!
                        <% else %>
                        <% @reviews.reverse_each do |review| %>
                          <div class="clearfix padding010 row-fluid">
                            <ul class="more-info pull-left span3">
                              <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Submitted by: <b><%= "#{review.user.first_name} #{review.user.last_name}" %></b>
                                    <% if current_user.try(:admin?) || current_user.id == review.user.id %>
                                      <small><%= link_to "Edit", edit_renter_review_path(@renter, id: review), class: "btn btn-primary btn-mini" %></small>
                                      <small><%= link_to "Delete", renter_review_path(@renter, id: review), method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "btn btn-danger btn-mini" %>         
                                      </small>
                                    <% end %>
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Lived Here:
                                  </span>
                                  <span class="qty pull-right">
                                    <%= review.years %> year(s)                                  
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Address Line 1:
                                  </span>
                                  <span class="qty pull-center">
                                    <br /><%= review.address1.titleize %>                                  
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Address Line 2:
                                  </span>
                                  <span class="qty pull-center">
                                    <br /><%= review.address2.titleize %>
                                  </span>
                                </li>
                            </ul>
                            <ul class="more-info pull-right span3">
                                <li class="info-label clearfix">
                                  <span class="qty pull-right">
                                    <div class="clearfix star-rating" data-score=<%= review.rating %>></div>
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Property:
                                  </span>
                                  <span class="qty pull-right">
                                    <%= PropertyType.find(review.property_type_id).name %>
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    City:
                                  </span>
                                  <span class="qty pull-right">
                                    <%= review.city.titleize %>
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    State:
                                  </span>
                                  <span class="qty pull-right">
                                    <%= review.state.upcase %>
                                  </span>
                                </li>
                                <li class="info-label clearfix">
                                  <span class="pull-left">
                                    Zipcode:
                                  </span>
                                  <span class="qty pull-right">
                                    <%= review.zipcode %>
                                  </span>
                                </li>
                            </ul>
                          </div>
                          <div class="clearfix padding10">
                            <h5><b>
                              Details:
                            </h5></b>
                            <%= simple_format(review.comment) %>
                          </div>
                          <hr><p><p><p>
                        <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <!-- .span8 -->
        <div class="span4">
            <div class="widget map box-container padding30">
                <h3 class="widget-title">Map &amp; Directions</h3>
                  <iframe
                    width="600"
                    height="450"
                    frameborder="0" style="border:0"
                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAOQYMDgVIAU7efjItrEydrbTO7g6hPpjU&q=<%= @renter.city %>, <%= @renter.state %>" allowfullscreen>
                  </iframe>
                  <dl class="margin0">
                    <dt>Current Location of <%= @renter.fname.titleize %> <%= @renter.lname.titleize %></dt>
                    <dd class="margin0"><%= @renter.city %>, <%= @renter.state %></dd>
                </dl>
            </div>
            <div class="search-form widget">
              <p>Find your next renter</p>
                <%= form_tag search_renters_path, method: :get do |f| %>
                  <%= text_field_tag :license, nil, placeholder: "Driver's License" %>
                  <%#= text_field_tag :id, nil, placeholder: "ID number" %>
                  <%# <%= text_field_tag :search, nil, placeholder: "John Doe" %>
                  <%# <%= text_field_tag :location, nil, placeholder: "Los Angeles, CA" %> 
                  <%= submit_tag 'Search', name: nil, class: "btn span2 btn-realto-form btn-small" %>
                <% end %>
            </div>
            <!-- .search-form -->
        </div>
        <!-- .span4 -->
    </div>
    <!-- .row -->
</div>
<!-- .container -->